### ISSUE TITLE
Training documentation

### ISSUE THREAD

**Issue by deepseek** [hirotomusiker/faster_rcnn_minimum#1]
@hirotomusiker How to train my own data?

**Comment by hirotomusiker** [comment]
Thank you for using my repo!
Unfortunately, this repo aims at understanding maskrcnn-benchmark's inference.
Please use [maskrcnn-benchmark](https://github.com/facebookresearch/maskrcnn-benchmark) for training.

**Comment by deepseek** [comment]
hmmmm...
